[project]
name = "deeplotx"
version = "0.4.1"
description = "Easy-2-use long text classifier trainers."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hf-xet>=1.0.5",
    "jupyter>=1.1.1",
    "numpy>=2.2.5",
    "python-dotenv>=1.1.0",
    "torch>=2.7.0",
    "transformers>=4.51.3",
    "typing-extensions>=4.13.2",
]
